### ISSUE TITLE
can do it with flutter ?

### ISSUE THREAD

**Issue by amr-muhammad-anwar** [Esri/arcgis-maps-sdk-flutter-samples#104]
import com.arcgismaps.httpcore.authentication.ArcGISAuthenticationChallenge
import com.arcgismaps.httpcore.authentication.ArcGISAuthenticationChallengeHandler
import com.arcgismaps.httpcore.authentication.ArcGISAuthenticationChallengeResponse
import com.arcgismaps.httpcore.authentication.ArcGISCredential

class AppAuthHandler (
    val createCredential:suspend() ->Result<ArcGISCredential>
): ArcGISAuthenticationChallengeHandler {
    override suspend fun handleArcGISAuthenticationChallenge(challenge: ArcGISAuthenticationChallenge):ArcGISAuthenticationChallengeResponse{
        val result=createCredential()
        return result.let{
            if(it.isSuccess){
                ArcGISAuthenticationChallengeResponse.ContinueWithCredential(it.getOrThrow())
            }else{
                ArcGISAuthenticationChallengeResponse.ContinueAndFailWithError(it.exceptionOrNull()!!)
            }
        }
    }
}

**Comment by PaulAllanSturm** [comment]
Take a look at the "Authenticate with token" sample, here: https://github.com/Esri/arcgis-maps-sdk-flutter-samples/blob/21fc8cb39085566b854df13a8404722ac22762b8/lib/samples/authenticate_with_token/authenticate_with_token_sample.dart#L200

It shows how to use `handleArcGISAuthenticationChallenge` to respond to an authentication challenge. Then it shows how to use `TokenCredential.createWithChallenge()` to create a credential, and then `challenge.continueWithCredential(credential)` to complete the challenge.

**Comment by amr-muhammad-anwar** [comment]
The method 'OAuthUserConfiguration' isn't defined for the type '_AuthenticateWithOAuthSampleState' 

can't import  OAuthUserConfiguration at AuthenticateWithOAuthSample 


import 'package:arcgis_maps/arcgis_maps.dart';
import 'package:arcgis_maps_sdk_flutter_samples/src/samples/setUp.dart';

**Comment by amr-muhammad-anwar** [comment]
<img width="1080" alt="Screenshot 2024-08-01 at 9 26 10 AM" src="https://github.com/user-attachments/assets/f6492738-bc73-4c02-8e4e-fff1542cd4ed">

**Comment by amr-muhammad-anwar** [comment]
<img width="811" alt="Screenshot 2024-08-01 at 2 58 47 PM" src="https://github.com/user-attachments/assets/884eab92-22ad-4e7d-99a3-2bc8a1656000">


@PaulAllanSturm 
@jenmerritt

**Comment by PaulAllanSturm** [comment]
Ah yes, OAuthUserConfiguration was added in Beta 2. Authentication won't work with the current Beta 1 package. Beta 2 will be released in a week or two.

**Comment by amr-muhammad-anwar** [comment]
thank you
