### ISSUE TITLE
[Failed] flutter pub upgrade

### ISSUE THREAD

**Issue by saleh-aleid** [Esri/arcgis-maps-sdk-flutter-samples#11]
flutter pub upgrade
Resolving dependencies... 
Because arcgis_maps_sdk_flutter_samples depends on arcgis_maps from path which
  doesn't exist (could not find package arcgis_maps at
  "../arcgis_maps_package"), version solving failed.

**Comment by jenmerritt** [comment]
Hi @saleh-aleid !

The samples application is expecting the `arcgis_maps_package` to be in the same parent directory as the Samples project:

```
parent_directory
   |
   |__ arcgis-maps-sdk-flutter-samples
   |
   |__ arcgis_maps_package
```

Have you signed up and downloaded the ArcGIS Maps SDK for Flutter Beta package? If not, you can do so [here](https://earlyadopter.esri.com/key/flutter).

If you have, you can either match the above directory layout, or, update the pubspec.yaml file to reference the location of where you have unpackaged the `arcgis_maps_package`, and then try the `flutter pub upgrade` command again:

https://github.com/Esri/arcgis-maps-sdk-flutter-samples/blob/8c440f0e0fc7950d20beee65155f115bd9ceb487/pubspec.yaml#L15

Change from `path: ../arcgis_maps_package` to `path: path/to/your/arcgis_maps_package`

Let me know if this solves things for you.

**Comment by jenmerritt** [comment]
Closing this issue as answered. Don't hesitate to reopen this issue or get in touch via our [Early Adopter](https://earlyadopter.esri.com/) forum if you have any other questions. Thank you!

Please note we will be releasing a Beta 2 release of ArcGIS Maps SDK for Flutter in just a few weeks in August.
