### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by nrbnlulu** [Esri/arcgis-maps-sdk-flutter-samples#115]
Hey, is desktop support to be expected?

**Comment by jenmerritt** [comment]
Hi - thanks for your question. I've also responded to your post on our Early Adopter forum with some follow up questions, so we can continue the conversation there. For completeness, I'll also provide an answer here.

For deployment targets we are initially supporting iOS and Android, with Windows and macOS supported as development hosts (but not as target platforms).

Supporting desktop as target platforms is on our longer-term roadmap. Your feedback helps us prioritize our future efforts, so your interest is noted.
