### ISSUE TITLE
Roadmap and release planning

### ISSUE THREAD

**Issue by SynaOne** [Esri/arcgis-maps-sdk-flutter-samples#116]
Hello there!

We will probably try to use your SDK soon in one of our project.
But we aren't very confident with it, indeed, since April 16th, there is no update while the project is still in Beta.
Is this intended?
Do you have a roadmap to share with us please?
Do you recommend to use Kotlin & Swift SDKs instead of this one for now?

Thanks!

**Comment by jenmerritt** [comment]
Hi there, thank you for reaching out!

We are very much an active product, though we are indeed still a new product. Our release cadence, along with all our Maps SDKs, is 3 releases per year - currently these generally fall in April, August and November. Our second Beta release is due in the next week. We are then aiming for our first production release (so you can license and deploy your apps) by the end of this year. Note that at this time, our API won't be feature complete - in that it won't have all the functionality that the other SDKs have - we will be working to reach feature parity over the following releases. You can review the Classes we do have readily available in our API reference documentation: https://developers.arcgis.com/flutter

We also recently did a livestream which I'd encourage you to catch up on to hear more about the background and our plans: https://www.youtube.com/live/q8dNajNocqM?si=Ws1i4MoP2gxrc-RR

Have you signed up for our Early Adopter program? https://earlyadopter.esri.com/flutter
From here you can join the activity in our user forum, which includes discussions about future plans, and also try out our Beta package and provide feedback to us on the sorts of features you require for your applications, and that can feed into our planning.

I hope this helps.
