### ISSUE TITLE
oAuth

### ISSUE THREAD

**Issue by amr-muhammad-anwar** [Esri/arcgis-maps-sdk-flutter-samples#126]
need to use handleArcGISAuthenticationChallenge ,
how to send challenge and how to get it 
<img width="811" alt="Screenshot 2024-08-19 at 1 52 22 PM" src="https://github.com/user-attachments/assets/16ff80d1-c03f-49d9-bd05-a3ca429e6a38">

**Comment by amr-muhammad-anwar** [comment]
<img width="811" alt="Screenshot 2024-08-19 at 1 54 45 PM" src="https://github.com/user-attachments/assets/0899d2e6-7b8e-4d6f-b44f-988707fc0b01">

my Credential

**Comment by amr-muhammad-anwar** [comment]
![image](https://github.com/user-attachments/assets/c9617f2b-ce94-4049-a2b8-d367cb964e28)
Why see it

**Comment by amr-muhammad-anwar** [comment]
used it at kotlin as
 val arcGISChallengeHandler = AppAuthHandler {
            OAuthApplicationCredential.create(
                portalUrl = portalUrl,
                clientId = clientId,
                clientSecret = clientSecret,
                tokenExpirationInterval = 10
            )
        }
        OAuthApplicationCredential.create

**Comment by PaulAllanSturm** [comment]
One difference from the Kotlin implementation is that you must set this value:
```dart
ArcGISEnvironment
        .authenticationManager.arcGISAuthenticationChallengeHandler = this;
```
You can set this in the "initState" method of the object that implements "ArcGISAuthenticationChallengeHandler".

The sample does that here: https://github.com/Esri/arcgis-maps-sdk-flutter-samples/blob/main/lib/samples/authenticate_with_oauth/authenticate_with_oauth_sample.dart#L50-L51

**Comment by PaulAllanSturm** [comment]
> Why see it

On iOS, the operating system shows this dialog when an app uses OAuth. This is controlled by the operating system. The app can't change this part of the OAuth workflow.

**Comment by amr-muhammad-anwar** [comment]
can i use  OAuthApplicationCredential not OAuthUserConfiguration

**Comment by amr-muhammad-anwar** [comment]
@PaulAllanSturm
why this error 
<img width="1126" alt="Screenshot 2024-09-01 at 3 36 11 PM" src="https://github.com/user-attachments/assets/ec9e9932-c2eb-4306-8b6c-28fc57e27b72">

<img width="960" alt="Screenshot 2024-09-01 at 3 37 46 PM" src="https://github.com/user-attachments/assets/71f4465a-ee3d-48a6-9870-0a1a3aad3e75">

**Comment by PaulAllanSturm** [comment]
The "max-age=00:00:00" error is due to the service sending a header that is not understood by the HTTP cache. It will be fixed in the next release. For now, you can disable the HTTP cache. You can disable the HTTP cache by adding this line to your `main` function:

```dart
void main() async {
  await ArcGISEnvironment.httpClient.cache.setEnabled(false);
  // ...
}
```

There is a bug in ArcGIS Enterprise 11.2 that sends the wrong value for the "max-age" header. That bug was fixed in ArcGIS Enterprise 11.3. If you can upgrade the service to Enterprise 11.3, that would also fix the problem, but it is easier to disable the HTTP cache on the client.

**Comment by PaulAllanSturm** [comment]
> can i use OAuthApplicationCredential not OAuthUserConfiguration

You can use OAuthApplicationCredential, but it is a different kind of authentication. You can read more about the different kinds of authentication here:

https://developers.arcgis.com/documentation/security-and-authentication/types-of-authentication/#authentication-comparison

**Comment by amr-muhammad-anwar** [comment]
thank you !
