### ISSUE TITLE
Replace deprecated `@UIApplicationMain`

### ISSUE THREAD

**Issue by contfedorov** [Esri/arcgis-maps-sdk-flutter-samples#136]
I've updated Flutter to 3.24.1, Dart to 3.5.1. After that, it forcibly updates `@UIApplicationMain` to `@main` in `ios/Runner/AppDelegate.swift`. Looks like it should be updated in samples repo also.

https://github.com/Esri/arcgis-maps-sdk-flutter-samples/blob/b9c00a787a75b9ace5e9350bffa94430391792ef/ios/Runner/AppDelegate.swift#L3-L7

**Comment by jenmerritt** [comment]
Hi there, thanks for your feedback. For our Beta 2 release we have system requirements on our Early Adopter site and we currently support Dart 3.4.3 and Flutter 3.22.2. That being said, we are aiming to upgrade our system requirements to Flutter 3.24 in our next release (targeted at November of this year) so we will look out for this change, thank you!

**Comment by contfedorov** [comment]
@jenmerritt 
Thank you, looking for updates!

**Comment by jenmerritt** [comment]
No problem - I will close out these issues as we have them covered internally. 

As an aside I'd also encourage you, if you haven't already, to check out our Early Adopter site forum if you have any other feedback on the SDK as you test it out, we really appreciate it. Thanks again for giving our Beta release a try!
