### ISSUE TITLE
Update command in installation guide

### ISSUE THREAD

**Issue by contfedorov** [Esri/arcgis-maps-sdk-flutter-samples#137]
Install guide in `arcgis_maps_package/doc/api/index.html`, Step 2, contains the following command to run un terminal:
```
dart pub add 'arcgis_maps:{\"path\":\"../arcgis_maps_package\"}'
```
Execution causes the following message:
```
Because <my_app_name> depends on arcgis_maps from unknown source "\"path\":\"../arcgis_maps_package\"", version solving failed.
```

Looks like it should be replaced with this one (without backslashes):
```
dart pub add 'arcgis_maps:{"path":"../arcgis_maps_package"}'
```

Executing the latter one causes expected installation:
```
Resolving dependencies... 
Downloading packages... 
  collection 1.18.0 (1.19.0 available)
  dio 5.6.0 (5.7.0 available)
  flutter_lints 3.0.2 (4.0.0 available)
...
```

**Comment by jenmerritt** [comment]
Hi there, thanks for your comment. We are aware that certain command-line tools have slightly different requirements for some of the formatting around the path - we've seen another case where the `'` around `arcgis_maps` is not required. We posted in our Early Adopter forum which is where we focus support for the product. I'll add this case to that post incase anyone else runs into it. 

In terms of going forward, we are now working towards our production release targeted for late November of this year and will be publishing the package on pub.dev, so thankfully these path variances should no longer be an issue.

**Comment by contfedorov** [comment]
@jenmerritt 
Thank you. My setup just in case:
- macOS Sonoma 14.5
- Flutter 3.24.1
- Dart 3.5.1

Looking for updates also!
