### ISSUE TITLE
Unable to run this sample code in my enviornment

### ISSUE THREAD

**Issue by aadijain725** [Esri/arcgis-maps-sdk-flutter-samples#204]
ArcGIS Maps SDK for Flutter Setup:
I have been trying to set up the ArcGIS Maps SDK for Flutter for the past three days but continue to encounter the following issue during the build process:

Could not determine the dependencies of task ':arcgis_maps:compileDebugKotlin'.  
> Unknown Kotlin JVM target: 21  

I have followed all the setup steps detailed on your [official documentation](https://developers.arcgis.com/flutter/) and even cloned this repo and tried to run the app, however I keep running into the same issue. 

Here is a detail on my system config:

[√] Flutter (Channel stable, 3.24.5, on Microsoft Windows [Version 10.0.19045.2965], locale en-IN)
    • Flutter version 3.24.5 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\aadi.jain\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.12.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Professional
    • Visual Studio Professional 2022 version 17.12.35521.163
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[√] VS Code (version 1.95.3)
    • VS Code at C:\Users\aadi.jain\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 15 (API 35) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19045.2965]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 131.0.6778.86
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 131.0.2903.70

[√] Network resources
    • All expected network resources are available.

I have tried running the app through both VS code and Android Studio, I am trying to run on a pixel 8a running android 15.0.

Please help.

**Comment by changanxian** [comment]
In Android Studio LadyBug, could you switch the  JDK 21 to JDK 17 in the `Setting -> Build Tools -> Gradle JDK Location`?
Or, run the following command:
```
flutter config --jdk-dir=<your-local-JDK-17-path>
```

**Comment by aadijain725** [comment]
That worked! Thank you so much.
