### ISSUE TITLE
unable to run sample code 

### ISSUE THREAD

**Issue by KaushalSalvatore** [Esri/arcgis-maps-sdk-flutter-samples#209]
[Uploading gis_sdk.pdf…]()
i am trying to run sdk sample but its continues giving me same error.

* What went wrong:
Execution failed for task ':arcgis_maps:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\arcgis_maps-200.6.0+4426\android\.cxx\Debug\2j1pee34\arm64-v8a'
  [1/2] Building C object CMakeFiles/arcgis_maps.dir/arcgis_maps.c.o
  [2/2] Linking C shared library "E:\flutter projects\arcgis-maps-sdk-flutter-samples-main\arcgis-maps-sdk-flutter-samples-main\build\arcgis_maps\intermediates\cxx\Debug\2j1pee34\obj\arm64-v8a\libarcgis_maps.so"
  FAILED: E:/flutter projects/arcgis-maps-sdk-flutter-samples-main/arcgis-maps-sdk-flutter-samples-main/build/arcgis_maps/intermediates/cxx/Debug/2j1pee34/obj/arm64-v8a/libarcgis_maps.so 
  cmd.exe /C "cd . && C:\Users\Lenovo\AppData\Local\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=aarch64-none-linux-android26 --sysroot=C:/Users/Lenovo/AppData/Local/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -fno-limit-debug-info  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libarcgis_maps.so -o "E:\flutter projects\arcgis-maps-sdk-flutter-samples-main\arcgis-maps-sdk-flutter-samples-main\build\arcgis_maps\intermediates\cxx\Debug\2j1pee34\obj\arm64-v8a\libarcgis_maps.so" CMakeFiles/arcgis_maps.dir/arcgis_maps.c.o -L"E:/flutter projects/arcgis-maps-sdk-flutter-samples-main/arcgis-maps-sdk-flutter-samples-main/build/arcgis_maps/intermediates/cxx/Debug/2j1pee34/obj/arm64-v8a/../../../../../../../../arcgis_maps_core/android/arm64-v8a" -lruntimecore  -larcgis_maps_ffi  -latomic -lm && cd ."
  ld: error: unable to find library -lruntimecore
  ld: error: unable to find library -larcgis_maps_ffi
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\Lenovo\\AppData\\Local\\Android\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\Lenovo\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\arcgis_maps-200.6.0+4426\\android\\.cxx\\Debug\\2j1pee34\\arm64-v8a" ^
        arcgis_maps
    from C:\Users\Lenovo\AppData\Local\Pub\Cache\hosted\pub.dev\arcgis_maps-200.6.0+4426\android

**Comment by jenmerritt** [comment]
Hi there, did this resolve your issue?

**Comment by KaushalSalvatore** [comment]
Yes thank you for your support

**Comment by jenmerritt** [comment]
Great to hear! I will close this as answered.
