### ISSUE TITLE
Error while running Display map 

### ISSUE THREAD

**Issue by vijaybadugu** [Esri/arcgis-maps-sdk-flutter-samples#210]
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':arcgis_maps:compileDebugKotlin'.
> Unknown Kotlin JVM target: 21

**Comment by changanxian** [comment]
Could you try the [solution](https://github.com/Esri/arcgis-maps-sdk-flutter-samples/issues/204#issuecomment-2517975529) of the closed issue?

**Comment by jenmerritt** [comment]
Further to the above, we have now published a blog article that shares the same solution, and should help resolve your issue: https://community.esri.com/t5/arcgis-maps-sdks-native-blog/solution-android-studio-ladybug-2024-2-1-and/ba-p/1567683

**Comment by jenmerritt** [comment]
Looks like this was resolved on the forums: https://community.esri.com/t5/flutter-maps-sdk-questions/flutter-build-error/m-p/1567039#M15

Closing.
